server.port=8080
spring.application.name=alertsiq-formbuilder

# Wells Fargo MongoDB Configurations
mongoDBConnectionAddress=dandrlm58010.wellsfargo.com:29000,m8dr0dan2ss002.wellsfargo.com:29000,dandrbm58012.wellsfargo.com:29000
mongoDBDataBase=s01_ang_content
mongoDBUserName=ANG_CONTENT_SIT_APP
mongoDBSocketConnectionTimeout=10000
mongoDBSocketReadTimeout=10000
mongoDBMaxConnection=10000
mongoDBCollectionName=CONTENT_TEMPLATE
mongoDBReplicaSet=rs_ddev2
mongoDBMinConnection=10
mongoDBPort=29000

# Encrypted MongoDB Password (AES Encrypted: "ANG_CONTENT_SIT_PWD_123")
mongoDBPassword.encrypted=g3z8q/R3rR9yS1Y1a2B3c4D5e6F7g8H9+I0J1K2L3M4=
encryption.secret.key=AlertsIQSecretKey

# Spring Boot Configuration
spring.main.allow-bean-definition-overriding=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Enable Swagger API docs path
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
